<?php
echo "<!DOCTYPE html>";
echo "<html>";
echo "    <head>";
echo "        <meta charset=\"utf-8\" />";
echo "        <link rel=\"stylesheet\" href=\"style.css\" />";
echo "        <title>Parking</title>";
echo "    </head>";
echo "  ";
echo "<body>";
echo "<style type=\"text/css\">";
echo "";
echo ".TitrePrincipale{";
echo "font-family: Bebas Neue;";
echo "font-size: 5em;";
echo "color: red;";
echo "position:absolute; ";
echo "left:200px;";
echo "}";
echo "";
echo ".TitreSecondaire{";
echo "font-family: Bebas Neue;";
echo "font-size: 3em;";
echo "position:absolute;";
echo "left:20px;";
echo "top:200px;";
echo "}";
echo "";
echo "";
echo ".button {";
echo "  border: none;";
echo "  color: white;";
echo "  padding: 16px 32px;";
echo "  text-align: center;";
echo "  text-decoration: none;";
echo "  display: inline-block;";
echo "  font-size: 16px;";
echo "  margin: 4px 2px;";
echo "  transition-duration: 0.4s;";
echo "  cursor: pointer;";
echo "}";
echo "";
echo ".button3 {";
echo "  background-color: white; ";
echo "  color: black; ";
echo "  border: 2px solid red;";
echo "}";
echo "";
echo ".button3:hover {";
echo "  background-color: red;";
echo "  color: white;";
echo "}";
echo "";
echo ".button2 {";
echo "  background-color: white; ";
echo "  color: black; ";
echo "  border: 2px solid blue;";
echo "}";
echo "";
echo ".button2:hover {";
echo "  background-color: blue;";
echo "  color: white;";
echo "}";
echo "";
echo ".button1 {";
echo "  background-color: white; ";
echo "  color: black; ";
echo "  border: 2px solid green;";
echo "}";
echo "";
echo ".button1:hover {";
echo "  background-color: green;";
echo "  color: white;";
echo "}";
echo "</style>";
echo "<div style=\"position:absolute; right:20px; top:25px\">";
echo "<button class=\"button button3\">Accueil</button>";
echo "<button class=\"button button2\" onclick=\"window.location.href='" . url('/dashboard') . "'\">Inscription</button>";
echo "<button class=\"button button1\">Réserver une place</button>";
echo "</div>";
echo "<div class=\"TitrePrincipale\"><STRONG><U>Parking</U><STRONG>";
echo "</div>";
echo "<div class =\"TitreSecondaire\"><STRONG><U>Accueil</U></STRONG>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "</body>";
echo "</html>";
?>